spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-jwt-security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: SPRINGBOOT-SECURITY 3.0
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000 # a day
      refresh-token:
        expiration: 180000 # 7 days

